# docker-compose.yml
version: "3"
services:
  algaeortho:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: algaeortho:0.1.0
    ports:
      - "8050:8050"
    volumes:
      - ./data:/data
    environment:
      SERVER_PORT: 8050
      DASH_DEBUG_MODE: True