name: algaeortho
channels:
  - etetoolkit
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - numpy=1.21.5
  - pip=21.2.4
  - python=3.9.12
  - requests=2.27.1
  - scipy=1.7.3
  - urllib3=1.26.8
  - clustalo=1.2.3
  - pip:
      - click==8.1.3
      - dash==2.8.0
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - flask==2.2.2
      - importlib-metadata==6.0.0
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - markupsafe==2.1.2
      - plotly==5.13.0
      - tenacity==8.1.0
      - werkzeug==2.2.2
      - zipp==3.12.0
      - pandas==1.5.3
      - biopython==1.78
      - dash_cytoscape==0.2.0
      - dash-bootstrap-components==1.4.1
      - dash-bootstrap-templates==1.0.8
